export default [
    { type: "coder", label: "Url编码", value: "urlEncode" },
    { type: "coder", label: "Url解码", value: "urlDecode" },
    { type: "coder", label: "Escape编码", value: "encodeURIComponent" },
    { type: "coder", label: "Escape解码", value: "decodeURIComponent" },
    { type: "coder", label: "Base64编码", value: "b64Encode" },
    { type: "coder", label: "Base64解码", value: "b64Decode" },
    { type: "coder", label: "Hex编码", value: "hexEncode" },
    { type: "coder", label: "Hex解码", value: "hexDecode" },
    { type: "coder", label: "Unicode编码", value: "unicodeEncode" },
    { type: "coder", label: "Unicode解码", value: "unicodeDecode" },
    { type: "coder", label: "实体编码", value: "entityEncode" },
    { type: "coder", label: "实体解码", value: "entityDecode" },
    { type: "coder", label: "转时间戳", value: "toTimestamp" },
    { type: "coder", label: "转日期时间", value: "toDateTime" },
    { type: "coder", label: "邮件编码", value: "quotePrintEncode" },
    { type: "coder", label: "邮件解码", value: "quotePrintDecode" },
]
